### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: |-
  Returns the number of qubits currently available to borrow.
  This includes unused qubits; that is, this includes the qubits
  returned by `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: |-
      The number of qubits that could be allocated in a `borrowing` statement.
      If the target machine being used does not provide this information, then
      `-1` is returned.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
...
