on:
  pull_request:
    branches:
    - master

jobs:
  check-samples-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check that samples branch refers to master.
        run: |
          Get-ChildItem | Write-Host;
          Get-Location | Write-Host;
          $configPath = ".openpublishing.publish.config.json";
          $config = Get-Content $configPath | ConvertFrom-Json;
          $samplesRepo = $config.dependent_repositories | Where-Object {
            $_.url -eq "https://github.com/microsoft/quantum"
          }
          if ($samplesRepo.branch -ne "master") {
            Write-Host "::error file=$configPath::Samples repository branch is not set to master for a PR targeting master."
          }
        shell: pwsh
